import React, { useState, useEffect } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { Layers } from "lucide-react";
import api from "../../services/api";
import toast from "react-hot-toast";
import { useAuth } from "../../store/AuthContext";
export default function AcceptInvitePage() {
  const [searchParams] = useSearchParams();
  const token = searchParams.get("token");
  const navigate = useNavigate();
  const { login } = useAuth();
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [email, setEmail] = useState(""); // Will be set after success useEffect(() => { if (!token) { setError('Invalid or missing invitation token.'); } }, [token]); const handleSubmit = async (e) => { e.preventDefault(); if (password !== confirmPassword) { setError('Passwords do not match'); return; } setLoading(true); setError(''); try { const res = await api.post('/public/accept-invite', { token, password }); setEmail(res.data.data.email); toast.success('Password set successfully! Logging you in...'); // Auto login await login(res.data.data.email, password); navigate('/'); // Go to dashboard } catch (err) { setError(err.response?.data?.message || 'Failed to accept invitation'); } finally { setLoading(false); } }; if (!token) { return ( <div className="min-h-screen bg-surface-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8"> <div className="sm:mx-auto sm:w-full sm:max-w-md text-center"> <Layers className="mx-auto h-12 w-12 text-primary" /> <h2 className="mt-6 text-center text-3xl font-display font-bold tracking-tight text-default"> Invalid Invitation </h2> <p className="mt-2 text-center text-sm text-muted"> The invitation link is missing or invalid. </p> </div> </div> ); } return ( <div className="min-h-screen bg-surface-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8 animate-fade-in"> <div className="sm:mx-auto sm:w-full sm:max-w-md"> <div className="flex justify-center"> <div className="p-3 bg-primary/10 rounded-xl"> <Layers className="h-8 w-8 text-primary" /> </div> </div> <h2 className="mt-6 text-center text-3xl font-display font-bold tracking-tight text-default"> Accept Invitation </h2> <p className="mt-2 text-center text-sm text-muted"> Welcome! Please set a secure password for your account. </p> </div> <div className="mt-8 sm:mx-auto sm:w-full sm:max-w-md"> <div className="bg-surface py-8 px-4 shadow-sm border border-border sm:rounded-xl sm:px-10"> <form className="space-y-6" onSubmit={handleSubmit}> {error && ( <div className="p-3 bg-red-500/10 border border-red-500/20 text-red-600 rounded-lg text-sm text-center"> {error} </div> )} <div> <label className="block text-sm font-medium mb-1"> New Password </label> <input type="password" required className="input w-full" value={password} onChange={(e) => setPassword(e.target.value)} /> </div> <div> <label className="block text-sm font-medium mb-1"> Confirm Password </label> <input type="password" required className="input w-full" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} /> </div> <button type="submit" disabled={loading} className="btn btn-primary w-full flex justify-center py-2.5" > {loading ? 'Setting Password...' : 'Save & Continue'} </button> </form> </div> </div> </div> );
}
