CREATE TABLE expenses (
    id VARCHAR(50) NOT NULL PRIMARY KEY,
    tenant_id VARCHAR(50) NOT NULL,
    category VARCHAR(100),
    description TEXT,
    vendor VARCHAR(255),
    employee VARCHAR(255),
    department VARCHAR(100),
    amount DECIMAL(15, 2),
    tax DECIMAL(15, 2),
    currency VARCHAR(10),
    payment_method VARCHAR(100),
    date DATE,
    status VARCHAR(50),
    notes TEXT,
    receipt BOOLEAN DEFAULT FALSE,
    tags TEXT,
    invoice_num VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_expenses_tenant_id (tenant_id),
    CONSTRAINT fk_expenses_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);
