-- V5: Dashboard metrics seed data
CREATE TABLE IF NOT EXISTS dashboard_metrics (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    metric_type VARCHAR(50) NOT NULL,
    metric_date DATE NOT NULL,
    metric_value DECIMAL(15,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_metric_type_date (metric_type, metric_date)
);

-- Seed 12 months of realistic mock data
INSERT INTO dashboard_metrics (metric_type, metric_date, metric_value) VALUES
-- MRR data
('mrr', DATE_SUB(CURDATE(), INTERVAL 11 MONTH), 42000.00),
('mrr', DATE_SUB(CURDATE(), INTERVAL 10 MONTH), 45500.00),
('mrr', DATE_SUB(CURDATE(), INTERVAL 9 MONTH), 48200.00),
('mrr', DATE_SUB(CURDATE(), INTERVAL 8 MONTH), 51000.00),
('mrr', DATE_SUB(CURDATE(), INTERVAL 7 MONTH), 53800.00),
('mrr', DATE_SUB(CURDATE(), INTERVAL 6 MONTH), 57200.00),
('mrr', DATE_SUB(CURDATE(), INTERVAL 5 MONTH), 61500.00),
('mrr', DATE_SUB(CURDATE(), INTERVAL 4 MONTH), 65000.00),
('mrr', DATE_SUB(CURDATE(), INTERVAL 3 MONTH), 69400.00),
('mrr', DATE_SUB(CURDATE(), INTERVAL 2 MONTH), 74200.00),
('mrr', DATE_SUB(CURDATE(), INTERVAL 1 MONTH), 79800.00),
('mrr', CURDATE(), 84600.00),
-- Active Subscriptions
('active_subscriptions', DATE_SUB(CURDATE(), INTERVAL 11 MONTH), 210),
('active_subscriptions', DATE_SUB(CURDATE(), INTERVAL 10 MONTH), 228),
('active_subscriptions', DATE_SUB(CURDATE(), INTERVAL 9 MONTH), 241),
('active_subscriptions', DATE_SUB(CURDATE(), INTERVAL 8 MONTH), 255),
('active_subscriptions', DATE_SUB(CURDATE(), INTERVAL 7 MONTH), 269),
('active_subscriptions', DATE_SUB(CURDATE(), INTERVAL 6 MONTH), 286),
('active_subscriptions', DATE_SUB(CURDATE(), INTERVAL 5 MONTH), 307),
('active_subscriptions', DATE_SUB(CURDATE(), INTERVAL 4 MONTH), 325),
('active_subscriptions', DATE_SUB(CURDATE(), INTERVAL 3 MONTH), 347),
('active_subscriptions', DATE_SUB(CURDATE(), INTERVAL 2 MONTH), 371),
('active_subscriptions', DATE_SUB(CURDATE(), INTERVAL 1 MONTH), 399),
('active_subscriptions', CURDATE(), 423),
-- Net Billing
('net_billing', DATE_SUB(CURDATE(), INTERVAL 11 MONTH), 38500.00),
('net_billing', DATE_SUB(CURDATE(), INTERVAL 10 MONTH), 41200.00),
('net_billing', DATE_SUB(CURDATE(), INTERVAL 9 MONTH), 44800.00),
('net_billing', DATE_SUB(CURDATE(), INTERVAL 8 MONTH), 47300.00),
('net_billing', DATE_SUB(CURDATE(), INTERVAL 7 MONTH), 50100.00),
('net_billing', DATE_SUB(CURDATE(), INTERVAL 6 MONTH), 53400.00),
('net_billing', DATE_SUB(CURDATE(), INTERVAL 5 MONTH), 57800.00),
('net_billing', DATE_SUB(CURDATE(), INTERVAL 4 MONTH), 61200.00),
('net_billing', DATE_SUB(CURDATE(), INTERVAL 3 MONTH), 65700.00),
('net_billing', DATE_SUB(CURDATE(), INTERVAL 2 MONTH), 70100.00),
('net_billing', DATE_SUB(CURDATE(), INTERVAL 1 MONTH), 75400.00),
('net_billing', CURDATE(), 80200.00),
-- Net Payments
('net_payments', DATE_SUB(CURDATE(), INTERVAL 11 MONTH), 36000.00),
('net_payments', DATE_SUB(CURDATE(), INTERVAL 10 MONTH), 39100.00),
('net_payments', DATE_SUB(CURDATE(), INTERVAL 9 MONTH), 42500.00),
('net_payments', DATE_SUB(CURDATE(), INTERVAL 8 MONTH), 45200.00),
('net_payments', DATE_SUB(CURDATE(), INTERVAL 7 MONTH), 48000.00),
('net_payments', DATE_SUB(CURDATE(), INTERVAL 6 MONTH), 51300.00),
('net_payments', DATE_SUB(CURDATE(), INTERVAL 5 MONTH), 55600.00),
('net_payments', DATE_SUB(CURDATE(), INTERVAL 4 MONTH), 59000.00),
('net_payments', DATE_SUB(CURDATE(), INTERVAL 3 MONTH), 63400.00),
('net_payments', DATE_SUB(CURDATE(), INTERVAL 2 MONTH), 67800.00),
('net_payments', DATE_SUB(CURDATE(), INTERVAL 1 MONTH), 73100.00),
('net_payments', CURDATE(), 77900.00),
-- Unpaid Invoices
('unpaid_invoices', DATE_SUB(CURDATE(), INTERVAL 11 MONTH), 4200.00),
('unpaid_invoices', DATE_SUB(CURDATE(), INTERVAL 10 MONTH), 3800.00),
('unpaid_invoices', DATE_SUB(CURDATE(), INTERVAL 9 MONTH), 4100.00),
('unpaid_invoices', DATE_SUB(CURDATE(), INTERVAL 8 MONTH), 3500.00),
('unpaid_invoices', DATE_SUB(CURDATE(), INTERVAL 7 MONTH), 3900.00),
('unpaid_invoices', DATE_SUB(CURDATE(), INTERVAL 6 MONTH), 4200.00),
('unpaid_invoices', DATE_SUB(CURDATE(), INTERVAL 5 MONTH), 3600.00),
('unpaid_invoices', DATE_SUB(CURDATE(), INTERVAL 4 MONTH), 4100.00),
('unpaid_invoices', DATE_SUB(CURDATE(), INTERVAL 3 MONTH), 3800.00),
('unpaid_invoices', DATE_SUB(CURDATE(), INTERVAL 2 MONTH), 4400.00),
('unpaid_invoices', DATE_SUB(CURDATE(), INTERVAL 1 MONTH), 4000.00),
('unpaid_invoices', CURDATE(), 4500.00);
